### ISSUE TITLE
Cannot log in with Github

### ISSUE THREAD

**Issue by GKaszewski** [oasis-sh/oasis#154]
As in title
![image](https://user-images.githubusercontent.com/42281413/116298878-4c7e9400-a79d-11eb-80bd-f7e5281f860b.png)

```
Uncaught (in promise) FirebaseError: Missing or insufficient permissions.
    at new e (https://oasis.sh/_next/static/chunks/ec5c9526.b00002c8385ee69f830c.js:1:1774)
    at https://oasis.sh/_next/static/chunks/ec5c9526.b00002c8385ee69f830c.js:1:152171
    at Ze.<anonymous> (https://oasis.sh/_next/static/chunks/ec5c9526.b00002c8385ee69f830c.js:1:151384)
    at It (https://oasis.sh/_next/static/chunks/483978de5ae00bb23ca9ff891b37fa73fa4376d2.af1fa64117069ccb745f.js:1:10633)
    at Ct (https://oasis.sh/_next/static/chunks/483978de5ae00bb23ca9ff891b37fa73fa4376d2.af1fa64117069ccb745f.js:1:10372)
    at ni.EeOn.ni.sa (https://oasis.sh/_next/static/chunks/483978de5ae00bb23ca9ff891b37fa73fa4376d2.af1fa64117069ccb745f.js:1:39289)
    at xn (https://oasis.sh/_next/static/chunks/483978de5ae00bb23ca9ff891b37fa73fa4376d2.af1fa64117069ccb745f.js:1:18899)
    at En (https://oasis.sh/_next/static/chunks/483978de5ae00bb23ca9ff891b37fa73fa4376d2.af1fa64117069ccb745f.js:1:16716)
    at dn.EeOn.o.Ca (https://oasis.sh/_next/static/chunks/483978de5ae00bb23ca9ff891b37fa73fa4376d2.af1fa64117069ccb745f.js:1:20957)
    at dn.EeOn.o.Xa (https://oasis.sh/_next/static/chunks/483978de5ae00bb23ca9ff891b37fa73fa4376d2.af1fa64117069ccb745f.js:1:20251)
```

**Comment by heybereket** [comment]
Hey, this has been fixed. It was an issue with our security rules via Firebase, thanks for spotting this bug! However, even after logging in you won't see anything *yet*, as we are still working on the redesign and features, stay tuned!
